/home/phuet/.ansible/collections/ansible_collections/community/general/tests/integration/targets/gitlab_deploy_key/tasks/main.yml
/home/phuet/.ansible/collections/ansible_collections/community/general/tests/integration/targets/gitlab_deploy_key/defaults/main.yml
/home/phuet/.ansible/collections/ansible_collections/community/general/tests/integration/targets/deploy_helper/tasks/main.yml
/home/phuet/.ansible/collections/ansible_collections/community/general/tests/integration/targets/deploy_helper/meta/main.yml
/home/phuet/.cache/go-build/github.com/openshift/baremetal-operator@v0.0.0-20200715132148-0f91f62a41fe/deploy/crds/kustomization.yaml
/home/phuet/.cache/go-build/github.com/openshift/baremetal-operator@v0.0.0-20200715132148-0f91f62a41fe/deploy/crds/metal3.io_baremetalhosts_crd.yaml
/home/phuet/.cache/go-build/github.com/openshift/baremetal-operator@v0.0.0-20200715132148-0f91f62a41fe/deploy/default/kustomization.yaml
/home/phuet/.cache/go-build/github.com/openshift/baremetal-operator@v0.0.0-20200715132148-0f91f62a41fe/deploy/default/kustomizeconfig.yaml
/home/phuet/.cache/go-build/github.com/openshift/baremetal-operator@v0.0.0-20200715132148-0f91f62a41fe/deploy/namespace/kustomization.yaml
/home/phuet/.cache/go-build/github.com/openshift/baremetal-operator@v0.0.0-20200715132148-0f91f62a41fe/deploy/namespace/namespace.yaml
/home/phuet/.cache/go-build/github.com/openshift/baremetal-operator@v0.0.0-20200715132148-0f91f62a41fe/deploy/operator/bmo.yaml
/home/phuet/.cache/go-build/github.com/openshift/baremetal-operator@v0.0.0-20200715132148-0f91f62a41fe/deploy/operator/kustomization.yaml
/home/phuet/.cache/go-build/github.com/openshift/baremetal-operator@v0.0.0-20200715132148-0f91f62a41fe/deploy/rbac/kustomization.yaml
/home/phuet/.cache/go-build/github.com/openshift/baremetal-operator@v0.0.0-20200715132148-0f91f62a41fe/deploy/rbac/role.yaml
/home/phuet/.cache/go-build/github.com/openshift/baremetal-operator@v0.0.0-20200715132148-0f91f62a41fe/deploy/rbac/role_binding.yaml
/home/phuet/.cache/go-build/github.com/openshift/baremetal-operator@v0.0.0-20200715132148-0f91f62a41fe/deploy/rbac/service_account.yaml
/home/phuet/.cache/go-build/github.com/openshift/baremetal-operator@v0.0.0-20200715132148-0f91f62a41fe/ironic-deployment/default/kustomization.yaml
/home/phuet/.cache/go-build/github.com/openshift/baremetal-operator@v0.0.0-20200715132148-0f91f62a41fe/ironic-deployment/ironic/ironic.yaml
/home/phuet/.cache/go-build/github.com/openshift/baremetal-operator@v0.0.0-20200715132148-0f91f62a41fe/ironic-deployment/ironic/kustomization.yaml
/home/phuet/.cache/go-build/github.com/openshift/baremetal-operator@v0.0.0-20200715132148-0f91f62a41fe/ironic-deployment/keepalived/keepalived_patch.yaml
/home/phuet/.cache/go-build/github.com/openshift/baremetal-operator@v0.0.0-20200715132148-0f91f62a41fe/ironic-deployment/keepalived/kustomization.yaml
/home/phuet/.cache/go-build/github.com/dgoodwin/hive@v0.0.0-20210121160047-23364b143670/config/controllers/deployment.yaml
/home/phuet/.cache/go-build/github.com/dgoodwin/hive@v0.0.0-20210121160047-23364b143670/config/crds/hive.openshift.io_clusterdeployments.yaml
/home/phuet/.cache/go-build/github.com/dgoodwin/hive@v0.0.0-20210121160047-23364b143670/config/hiveadmission/clusterdeployment-webhook.yaml
/home/phuet/.cache/go-build/github.com/dgoodwin/hive@v0.0.0-20210121160047-23364b143670/config/hiveadmission/deployment.yaml
/home/phuet/.cache/go-build/github.com/dgoodwin/hive@v0.0.0-20210121160047-23364b143670/config/operator/operator_deployment.yaml
/home/phuet/.cache/go-build/github.com/dgoodwin/hive@v0.0.0-20210121160047-23364b143670/config/prometheus/prometheus-deployment-with-pvc.yaml
/home/phuet/.cache/go-build/github.com/dgoodwin/hive@v0.0.0-20210121160047-23364b143670/config/prometheus/prometheus-deployment.yaml
/home/phuet/.cache/go-build/github.com/dgoodwin/hive@v0.0.0-20210121160047-23364b143670/config/samples/hive_v1_clusterdeployment.yaml
/home/phuet/.cache/go-build/github.com/dgoodwin/hive@v0.0.0-20210121160047-23364b143670/config/templates/cluster-deployment-customimageset.yaml
/home/phuet/.cache/go-build/github.com/dgoodwin/hive@v0.0.0-20210121160047-23364b143670/config/templates/cluster-deployment.yaml
/home/phuet/.cache/go-build/github.com/moby/moby@v1.13.1/integration-cli/fixtures/deploy/default.yaml
/home/phuet/.cache/go-build/github.com/moby/moby@v1.13.1/integration-cli/fixtures/deploy/remove.yaml
/home/phuet/.cache/go-build/github.com/moby/moby@v1.13.1/integration-cli/fixtures/deploy/secrets.yaml
/home/phuet/.cache/go-build/sigs.k8s.io/structured-merge-diff@v1.0.2/internal/testdata/k8s-deployment.yaml
/home/phuet/.cache/go-build/sigs.k8s.io/structured-merge-diff/v4@v4.0.1/internal/testdata/k8s-deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/demo/sctp/resources/deployment-client.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/demo/sctp/resources/deployment-server-debug.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/demo/sctp/resources/deployment-server.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/exchange/deployment-sample.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/exchange/deployment-sample2.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/exchange/deployment-sample3.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/helm-charts/aic-vdu/charts/healing-controller/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/helm-charts/aic-vdu/charts/kubeapisymptomdataprovider/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/helm-charts/aic-vdu/charts/logservice/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/helm-charts/aic-vdu/charts/lwsd/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/helm-charts/aic-vdu/charts/pm/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/helm-charts/aic-vdu/charts/rcpsdl/templates/sdl-deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/helm-charts/aic-vdu/charts/rcpum/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/helm-charts/aic-vdu/charts/trsconfig/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/helm-charts/aic-vdu/templates/oamcp-deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/helm-charts/aic-vdu/templates/uprt-deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/HelmChart_2446/aic-vdu/charts/aic-vdu-oamcp/templates/oamcp-deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/HelmChart_2446/aic-vdu/charts/aic-vdu-up/templates/uprt-deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/HelmChart_2446/aic-vdu/charts/certificate-management/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/HelmChart_2446/aic-vdu/charts/healing-controller/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/HelmChart_2446/aic-vdu/charts/kubeapisymptomdataprovider/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/HelmChart_2446/aic-vdu/charts/logservice/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/HelmChart_2446/aic-vdu/charts/lwsd/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/HelmChart_2446/aic-vdu/charts/rcpum/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/HelmChart_2446/aic-vdu/charts/trsconfig/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/vdu_2592/HelmChart/aic-vdu/charts/aic-vdu-oamcp/templates/oamcp-deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/vdu_2592/HelmChart/aic-vdu/charts/aic-vdu-up/templates/uprt-deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/vdu_2592/HelmChart/aic-vdu/charts/certificate-management/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/vdu_2592/HelmChart/aic-vdu/charts/healing-controller/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/vdu_2592/HelmChart/aic-vdu/charts/kubeapisymptomdataprovider/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/vdu_2592/HelmChart/aic-vdu/charts/logservice/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/vdu_2592/HelmChart/aic-vdu/charts/lwsd/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/vdu_2592/HelmChart/aic-vdu/charts/rcpum/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/vdu_2592/HelmChart/aic-vdu/charts/trsconfig/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/vdu_2592/original/HelmChart/aic-vdu/charts/kubeapisymptomdataprovider/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/vdu_2592/original/HelmChart/aic-vdu/charts/rcpum/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/vdu_2592/original/HelmChart/aic-vdu/charts/aic-vdu-oamcp/templates/oamcp-deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/vdu_2592/original/HelmChart/aic-vdu/charts/certificate-management/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/vdu_2592/original/HelmChart/aic-vdu/charts/healing-controller/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/vdu_2592/original/HelmChart/aic-vdu/charts/trsconfig/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/vdu_2592/original/HelmChart/aic-vdu/charts/aic-vdu-up/templates/uprt-deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/vdu_2592/original/HelmChart/aic-vdu/charts/logservice/templates/deployment.yaml
/home/phuet/POC-NOKIA/poc-nokia-mn/helm/vdu_2592/original/HelmChart/aic-vdu/charts/lwsd/templates/deployment.yaml
/home/phuet/linuxptp-daemon/deploy/00-ns.yaml
/home/phuet/linuxptp-daemon/deploy/01-sa.yaml
/home/phuet/linuxptp-daemon/deploy/02-rbac.yaml
/home/phuet/linuxptp-daemon/deploy/linuxptp-daemon.yaml
/home/phuet/deploy/deployment.yaml
/home/phuet/deploy/deployment-arm.yaml
/home/phuet/deploy/objects/deployment.yaml
/home/phuet/deploy/objects/role.yaml
/home/phuet/deploy/objects/deployment-arm.yaml
/home/phuet/deploy/objects/clusterrole.yaml
/home/phuet/deploy/objects/class.yaml
/home/phuet/deploy/objects/serviceaccount.yaml
/home/phuet/deploy/objects/clusterrolebinding.yaml
/home/phuet/deploy/objects/rolebinding.yaml
/home/phuet/deploy/rbac.yaml
/home/phuet/deploy/class.yaml
/home/phuet/deploy/test-claim.yaml
/home/phuet/deploy/test-pod.yaml
/home/phuet/lab/linuxptp-daemon/deploy/00-ns.yaml
/home/phuet/lab/linuxptp-daemon/deploy/01-sa.yaml
/home/phuet/lab/linuxptp-daemon/deploy/02-rbac.yaml
/home/phuet/lab/linuxptp-daemon/deploy/linuxptp-daemon.yaml
/home/phuet/devel/inspektor-gadget/openshift/deployment.yaml
/home/phuet/devel/MEETUP-DEMO/vue-todos-container/helm/vue-todos/templates/deployment.yaml
/home/phuet/devel/MEETUP-DEMO/parallel-caps-container/helm/devsecops-demo/templates/deployment.yaml
/home/phuet/devel/service-telemetry-operator/build/stf-run-ci/tasks/deploy_stf.yml
/home/phuet/devel/service-telemetry-operator/deploy/alerts/alerts.yaml
/home/phuet/devel/service-telemetry-operator/deploy/crds/infra.watch_servicetelemetrys_crd.yaml
/home/phuet/devel/service-telemetry-operator/deploy/crds/infra.watch_v1alpha1_servicetelemetry_cr.yaml
/home/phuet/devel/service-telemetry-operator/deploy/crds/infra.watch_v1beta1_servicetelemetry_cr.yaml
/home/phuet/devel/service-telemetry-operator/deploy/olm-catalog/service-telemetry-operator/manifests/infra.watch_servicetelemetrys_crd.yaml
/home/phuet/devel/service-telemetry-operator/deploy/olm-catalog/service-telemetry-operator/manifests/service-telemetry-operator.clusterserviceversion.yaml
/home/phuet/devel/service-telemetry-operator/deploy/olm-catalog/service-telemetry-operator/metadata/annotations.yaml
/home/phuet/devel/service-telemetry-operator/deploy/operator.yaml
/home/phuet/devel/service-telemetry-operator/deploy/operator_group.yaml
/home/phuet/devel/service-telemetry-operator/deploy/role.yaml
/home/phuet/devel/service-telemetry-operator/deploy/role_binding.yaml
/home/phuet/devel/service-telemetry-operator/deploy/service_account.yaml
/home/phuet/devel/service-telemetry-operator/tests/performance-test/deploy/config/test-configs.yml
/home/phuet/devel/service-telemetry-operator/tests/performance-test/deploy/prom-servicemonitor.yml
/home/phuet/devel/service-telemetry-operator/tests/performance-test/deploy/qdr-servicemonitor.yml
/home/phuet/devel/service-telemetry-operator/tests/performance-test/deploy/qdrouterd.yaml
/home/phuet/devel/service-telemetry-operator/tests/performance-test/grafana/grafana-deploy.yml
/home/phuet/devel/ibm-nokia-lab/02-istio/deploy-nginx.yaml
/home/phuet/devel/ibm-nokia-lab/tools/deploy-net.yaml
/home/phuet/devel/ibm-nokia-lab/03-noport/deploy-nginx.yaml
/home/phuet/devel/ibm-nokia-lab/03-noport/deploy-nginx-noport.yaml
/home/phuet/deploy.yaml
/home/phuet/go/pkg/mod/sigs.k8s.io/kustomize@v2.0.3+incompatible/examples/helloWorld/deployment.yaml
/home/phuet/go/pkg/mod/sigs.k8s.io/kustomize@v2.0.3+incompatible/examples/ldap/base/deployment.yaml
/home/phuet/go/pkg/mod/sigs.k8s.io/kustomize@v2.0.3+incompatible/examples/ldap/overlays/production/deployment.yaml
/home/phuet/go/pkg/mod/sigs.k8s.io/kustomize@v2.0.3+incompatible/examples/ldap/overlays/staging/deployment.yaml
/home/phuet/go/pkg/mod/sigs.k8s.io/kustomize@v2.0.3+incompatible/examples/mySql/deployment.yaml
/home/phuet/go/pkg/mod/sigs.k8s.io/kustomize@v2.0.3+incompatible/examples/springboot/base/deployment.yaml
/home/phuet/go/pkg/mod/sigs.k8s.io/kustomize@v2.0.3+incompatible/examples/wordpress/mysql/deployment.yaml
/home/phuet/go/pkg/mod/sigs.k8s.io/kustomize@v2.0.3+incompatible/examples/wordpress/wordpress/deployment.yaml
/home/phuet/go/pkg/mod/k8s.io/cli-runtime@v0.17.4/artifacts/kustomization/deployment.yaml
/home/phuet/assisted-installer/assisted-service/deploy/assisted-installer-ingress-tls.yaml
/home/phuet/assisted-installer/assisted-service/deploy/assisted-installer-ingress.yaml
/home/phuet/assisted-installer/assisted-service/deploy/assisted-installer-sso.yaml
/home/phuet/assisted-installer/assisted-service/deploy/assisted-service-configmap.yaml
/home/phuet/assisted-installer/assisted-service/deploy/assisted-service-service.yaml
/home/phuet/assisted-installer/assisted-service/deploy/assisted-service.yaml
/home/phuet/assisted-installer/assisted-service/deploy/monitoring/grafana/assisted-installer-grafana-dashboard.yaml
/home/phuet/assisted-installer/assisted-service/deploy/monitoring/grafana/assisted-installer-k8s-grafana.yaml
/home/phuet/assisted-installer/assisted-service/deploy/monitoring/grafana/assisted-installer-ocp-grafana-route.yaml
/home/phuet/assisted-installer/assisted-service/deploy/monitoring/grafana/assisted-installer-ocp-grafana.yaml
/home/phuet/assisted-installer/assisted-service/deploy/monitoring/grafana/grafana-dashboards.yaml
/home/phuet/assisted-installer/assisted-service/deploy/monitoring/prometheus/assisted-installer-k8s-prometheus-subscription-instance.yaml
/home/phuet/assisted-installer/assisted-service/deploy/monitoring/prometheus/assisted-installer-k8s-prometheus-svc.yaml
/home/phuet/assisted-installer/assisted-service/deploy/monitoring/prometheus/assisted-installer-ocp-prometheus-custom-ca.yaml
/home/phuet/assisted-installer/assisted-service/deploy/monitoring/prometheus/assisted-installer-ocp-prometheus-route.yaml
/home/phuet/assisted-installer/assisted-service/deploy/monitoring/prometheus/assisted-installer-ocp-prometheus-subscription-instance.yaml
/home/phuet/assisted-installer/assisted-service/deploy/monitoring/prometheus/assisted-installer-ocp-prometheus-svc.yaml
/home/phuet/assisted-installer/assisted-service/deploy/monitoring/prometheus/assisted-installer-operator-group.yaml
/home/phuet/assisted-installer/assisted-service/deploy/monitoring/prometheus/assisted-installer-operator-subscription.yaml
/home/phuet/assisted-installer/assisted-service/deploy/monitoring/prometheus/assisted-installer-prometheus-svc-monitor.yaml
/home/phuet/assisted-installer/assisted-service/deploy/namespace/namespace.yaml
/home/phuet/assisted-installer/assisted-service/deploy/postgres/postgres-deployment-ephemeral.yaml
/home/phuet/assisted-installer/assisted-service/deploy/postgres/postgres-deployment.yaml
/home/phuet/assisted-installer/assisted-service/deploy/postgres/postgres-secret.yaml
/home/phuet/assisted-installer/assisted-service/deploy/postgres/postgres-storage.yaml
/home/phuet/assisted-installer/assisted-service/deploy/roles/default_role.yaml
/home/phuet/assisted-installer/assisted-service/deploy/roles/ocp_role.yaml
/home/phuet/assisted-installer/assisted-service/deploy/route53/route53-secret.yaml
/home/phuet/assisted-installer/assisted-service/deploy/s3/scality-deployment.yaml
/home/phuet/assisted-installer/assisted-service/deploy/s3/scality-public-secret.yaml
/home/phuet/assisted-installer/assisted-service/deploy/s3/scality-secret.yaml
/home/phuet/assisted-installer/assisted-service/deploy/s3/scality-storage.yaml
/home/phuet/assisted-installer/assisted-service/deploy/ui/ui_ingress.yaml
/home/phuet/assisted-installer/assisted-service/deploy/wiremock/wiremock-deployment.yaml
/home/phuet/assisted-installer/assisted-service/internal/controller/config/crd/bases/hive.openshift.io_clusterdeployments.yaml
/home/phuet/assisted-installer/assisted-service/openshift/template-post-deploy-job.yaml
