apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lldpd
  labels:
    tier: node
    app: lldpd
spec:
  selector:
    matchLabels:
      name: lldpd
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: lldpd
        name: lldpd
    spec:
      hostNetwork: true
      serviceAccountName: lldpad
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: lldpd
        imagePullPolicy: Always
        securityContext:
          privileged: true
          runAsUser: 1001
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_CHROOT
            - FOWNER
        image: quay.io/xymox/lldpd-ubi8:0.0.1
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: LLDPAD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          exec:
            command:
            - /check-liveness.sh
          initialDelaySeconds: 5
          periodSeconds: 15
        startupProbe:
          exec:
            command:
            - /check-liveness.sh
          initialDelaySeconds: 5
          periodSeconds: 15
        resources:
          requests:
            memory: "50Mi"
            cpu: "20m"
          limits:
            memory: "50Mi"
            cpu: "50m"
