apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lldpad
  labels:
    tier: node
    app: lldpad
spec:
  selector:
    matchLabels:
      name: lldpad
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: lldpad
        name: lldpad
    spec:
      hostNetwork: true
      serviceAccount: lldpad
      serviceAccountName: lldpad
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: lldpad
        image: quay.io/xymox/lldpad-ubi8:0.0.1
        imagePullPolicy: Always
        command:
        - /bin/bash
        - -c
        - --
        args:
        - /usr/sbin/lldpad -p -V 6
        env:
        - name: LLDPAD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "250m"
        securityContext:
          runAsUser: 0
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
