apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lldpad
  labels:
    tier: node
    app: lldpad
spec:
  selector:
    matchLabels:
      name: lldpad
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: lldpad
        name: lldpad
    spec:
      hostNetwork: true
      serviceAccountName: lldpad
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - operator: Exists
        effect: NoSchedule
      containers:
      - name: lldpad
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
        image: quay.io/xymox/lldpad-ubi8:0.0.1
        command:
        - /bin/bash
        - -c
        - --
        args:
        - /usr/sbin/lldpad -p -V 6
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: LLDPAD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          exec:
            command:
            - /check-liveness.sh
          initialDelaySeconds: 5
          periodSeconds: 15
        startupProbe:
          exec:
            command:
            - /check-liveness.sh
          initialDelaySeconds: 30
          periodSeconds: 5
        resources:
          requests:
            memory: "50Mi"
            cpu: "20m"
          limits:
            memory: "50Mi"
            cpu: "50m"
