---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: lldpad-rolebinding
subjects:
- kind: ServiceAccount
  name: lldpad
roleRef:
  kind: Role
  name: lldpad-role
  apiGroup: rbac.authorization.k8s.io
